# Generated by Django 4.2.3 on 2023-07-30 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Enter your Company Name', max_length=50)),
                ('company_contact_no', models.IntegerField(blank=True, help_text='Enter Company Phone Number')),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('part_number', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(help_text='Enter Branch Name', max_length=50)),
                ('loc_poc_contact_no', models.IntegerField(blank=True, help_text='Enter Company Phone Number')),
                ('loc_address', models.TextField()),
                ('loc_company', models.ForeignKey(help_text='Select Company Name', on_delete=django.db.models.deletion.PROTECT, to='masters.company')),
            ],
        ),
    ]
