# Generated by Django 4.0.5 on 2023-08-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_self_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='loc_poc_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
