# Generated by Django 4.2.4 on 2023-10-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_remove_amc_product'),
        ('masters', '0002_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='amc.amc'),
        ),
    ]
