# Generated by Django 4.2.4 on 2023-09-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_company_is_customer_company_is_self_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
