# Generated by Django 4.2.4 on 2023-11-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_suffix',
            field=models.CharField(default='test', help_text='Enter your Company Suffix', max_length=10),
            preserve_default=False,
        ),
    ]
