# Generated by Django 4.2.4 on 2023-12-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_alter_company_company_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_contact_no',
            field=models.BigIntegerField(blank=True, help_text='Enter Company Phone Number'),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_poc_contact_no',
            field=models.BigIntegerField(blank=True, help_text='Enter Company Phone Number'),
        ),
    ]
