# Generated by Django 4.2.4 on 2023-08-21 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0002_company_is_customer_company_is_self_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('update', models.TextField()),
                ('field_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField()),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=50, null=True)),
                ('issue', models.TextField()),
                ('downtime_required', models.BooleanField(default=False)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('spare_by_zaco', models.BooleanField(default=False)),
                ('spare_available', models.BooleanField(default=False)),
                ('cost', models.CharField(max_length=150)),
                ('amount_return', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Closed', 'Closed'), ('Hold', 'Hold')], default='Pending', max_length=100)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Mid', 'Mid'), ('Low', 'Low')], default='Mid', max_length=100)),
                ('feedback', models.TextField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.location')),
                ('sr_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket_call_time', models.ManyToManyField(blank=True, to='support.call_time')),
                ('ticket_document', models.ManyToManyField(blank=True, related_name='ticket_documents_no', to='support.document')),
                ('ticket_message', models.ManyToManyField(blank=True, to='support.message')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='ticket_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket'),
        ),
        migrations.AddField(
            model_name='document',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_no', to='support.ticket'),
        ),
        migrations.AddField(
            model_name='call_time',
            name='ticket_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call', to='support.ticket'),
        ),
    ]
