# Generated by Django 4.2.4 on 2023-10-09 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('update', models.TextField(blank=True, null=True)),
                ('field_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.TextField()),
                ('sent_on', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('location_text', models.CharField(blank=True, max_length=50, null=True)),
                ('issue', models.TextField()),
                ('downtime_required', models.BooleanField(default=False)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('spare_by_zaco', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Closed', 'Closed'), ('Hold', 'Hold')], default='Pending', max_length=100)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Mid', 'Mid'), ('Low', 'Low')], default='Mid', max_length=100)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('problem', models.TextField(blank=True, null=True)),
                ('fe_cost', models.IntegerField(blank=True, null=True)),
                ('spare_cost', models.IntegerField(blank=True, null=True)),
                ('transport_cost', models.IntegerField(blank=True, null=True)),
                ('amount_return', models.IntegerField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.company')),
                ('documents', models.ManyToManyField(blank=True, to='support.document')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.location')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.product')),
                ('sr_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket_call_time', models.ManyToManyField(blank=True, to='support.call_time')),
                ('ticket_message', models.ManyToManyField(blank=True, to='support.message')),
            ],
        ),
        migrations.AddField(
            model_name='call_time',
            name='ticket_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_call_times', to='support.ticket'),
        ),
    ]
