# Generated by Django 4.2.4 on 2023-09-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
