# Generated by Django 4.2.4 on 2023-08-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
