# Generated by Django 4.2.4 on 2023-09-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticket_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
