# Generated by Django 4.2.4 on 2023-08-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_message_sent_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='location_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
