# Generated by Django 4.2.4 on 2023-11-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_ticket_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
