# Generated by Django 4.2.4 on 2023-09-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_rename_ticket_document_ticket_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='documents',
            field=models.ManyToManyField(blank=True, to='support.document'),
        ),
    ]
