# Generated by Django 4.2.4 on 2023-09-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_call_time_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_time',
            name='update',
            field=models.TextField(blank=True, null=True),
        ),
    ]
