# Generated by Django 4.2.4 on 2023-09-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_ticket_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call_time',
            name='ticket_no',
        ),
        migrations.RemoveField(
            model_name='message',
            name='ticket_no',
        ),
    ]
