# Generated by Django 4.2.4 on 2023-11-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_ticket_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(default=1, upload_to='message/'),
            preserve_default=False,
        ),
    ]
