# Generated by Django 4.2.4 on 2023-11-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_remove_message_file_messagedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call_time',
            name='update',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
