# Generated by Django 4.2.4 on 2023-10-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_ticket_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='cost',
        ),
        migrations.AddField(
            model_name='ticket',
            name='fe_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='spare_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='transport_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='amount_return',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
