# Generated by Django 4.2.4 on 2023-11-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_calldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldocument',
            name='call_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.call_time'),
        ),
        migrations.AlterField(
            model_name='calldocument',
            name='file',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
