# Generated by Django 4.2.4 on 2023-12-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_ticket_raised_by_alter_ticket_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.BigIntegerField(max_length=50),
        ),
    ]
