# Generated by Django 4.2.4 on 2023-12-26 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_alter_ticket_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='spare_cost',
        ),
        migrations.CreateModel(
            name='SpareCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('part_no', models.CharField(max_length=50)),
                ('sr_no', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='spare_cost',
            field=models.ManyToManyField(blank=True, related_name='spare_cost', to='support.sparecost'),
        ),
    ]
