# Generated by Django 4.2.4 on 2024-03-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_ticket_sales_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
