# Generated by Django 4.2.4 on 2024-04-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_ticket_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.BigIntegerField(blank=True, help_text='Enter Phone Number', null=True),
        ),
    ]
