# Generated by Django 4.2.3 on 2023-07-30 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('startdate', models.DateTimeField()),
                ('duration', models.DateTimeField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.location')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.product')),
            ],
        ),
    ]
