# Generated by Django 4.2.4 on 2023-09-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0003_remove_product_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('startdate', models.DateField()),
                ('duration', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.product')),
            ],
        ),
    ]
