# Generated by Django 4.2.4 on 2023-09-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amc',
            name='duration',
        ),
        migrations.AddField(
            model_name='amc',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
