# Generated by Django 4.2.4 on 2023-10-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amc',
            name='escalation_matrix_1',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='escalation_matrix_2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='escalation_matrix_3',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='escalation_matrix_4',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
