# Generated by Django 4.2.4 on 2023-10-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0002_alter_amc_escalation_matrix_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amc',
            name='product',
        ),
    ]
