# Generated by Django 4.0.5 on 2023-08-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amc',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
