# Generated by Django 4.2.4 on 2023-10-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_remove_amc_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amc',
            name='location',
        ),
    ]
