# Generated by Django 4.0.5 on 2023-08-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_alter_amc_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amc',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='amc',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='amc',
            name='serial_number',
        ),
    ]
