# Generated by Django 4.0.5 on 2023-08-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0004_rename_product_name_amc_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amc',
            name='user',
        ),
    ]
