# Generated by Django 4.2.4 on 2023-10-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0004_remove_amc_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amc',
            old_name='description',
            new_name='amc_description',
        ),
    ]
