# Generated by Django 4.2.4 on 2023-11-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0005_rename_description_amc_amc_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc',
            name='file',
            field=models.FileField(default=1, upload_to='sla/'),
            preserve_default=False,
        ),
    ]
