# Generated by Django 4.2.4 on 2023-11-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0006_amc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc',
            name='uuid',
            field=models.CharField(default=1, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
