# Generated by Django 4.2.4 on 2023-12-28 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amc', '0008_amc_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc',
            name='config',
            field=models.FileField(blank=True, null=True, upload_to='config/'),
        ),
        migrations.AddField(
            model_name='amc',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoice/'),
        ),
        migrations.AddField(
            model_name='amc',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to='log/'),
        ),
        migrations.AddField(
            model_name='amc',
            name='po',
            field=models.FileField(blank=True, null=True, upload_to='po/'),
        ),
        migrations.AddField(
            model_name='amc',
            name='sla_file',
            field=models.FileField(blank=True, null=True, upload_to='sla/'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='amc/'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
