# Generated by Django 4.2.4 on 2023-10-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='aadhar',
            new_name='aadhaar_no',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='covid',
            new_name='covid_cert',
        ),
        migrations.AddField(
            model_name='user',
            name='is_salesperson',
            field=models.BooleanField(default=False),
        ),
    ]
