# Generated by Django 4.0.5 on 2023-08-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_customer_user_user_is_service_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_customer_admin',
            field=models.BooleanField(default=False),
        ),
    ]
