# Generated by Django 4.2.4 on 2023-12-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_aadhar_user_aadhaar_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_contact_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
