# Generated by Django 4.2.4 on 2023-09-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_user_email_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_field_engineer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sr_engineer',
            field=models.BooleanField(default=False),
        ),
    ]
