# Generated by Django 4.2.4 on 2023-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_field_engineer_user_is_sr_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar',
            field=models.FileField(blank=True, null=True, upload_to='user/'),
        ),
        migrations.AddField(
            model_name='user',
            name='covid',
            field=models.FileField(blank=True, null=True, upload_to='user/'),
        ),
    ]
