# Generated by Django 4.2.4 on 2024-11-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='region',
            field=models.ManyToManyField(to='partner.region'),
        ),
        migrations.DeleteModel(
            name='EngineerLocation',
        ),
    ]
