# Generated by Django 4.2.4 on 2024-11-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_engineer_region_delete_engineerlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='pin',
            field=models.IntegerField(default=0),
        ),
    ]
